# Generated by Django 5.2 on 2025-05-11 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begendigi_filmler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='begenmeyenler',
            field=models.ManyToManyField(blank=True, related_name='begenmedigi_filmler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='favoriler',
            field=models.ManyToManyField(blank=True, related_name='favori_filmler', to=settings.AUTH_USER_MODEL),
        ),
    ]
